spring.application.name=Nhom8

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/nhom8_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


app.jwt.secret=9a67475d868a287f3980753f7c4e5e7834241e8c7c94541e2d451a668478465d
app.jwt.expirationMs=86400000

